name: rust test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  rust_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: start pulsar container
        run: docker run -d -p 6650:6650 -p 8080:8080 apachepulsar/pulsar:2.10.1 /pulsar/bin/pulsar standalone --no-functions-worker --no-stream-storage
      - name: Wait for pulsar start
        run: sleep 30
      - name: Run unit tests
        run: cargo test
