name: rust test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rust_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup pulsar
        uses: shoothzj/setup-pulsar-action@v1
      - name: Run unit tests
        run: cargo test
